apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: egate-argo-product
  namespace: argocd 
spec:
  project: default

  source:
    repoURL: https://github.com/vcatss/egate-deploy.git
    targetRevision: HEAD
    path: pro
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
