apiVersion: apps/v1
kind: Deployment
metadata:
  name: egate-dev
spec:
  selector:
    matchLabels:
      app: egate-dev
  replicas: 2
  template:
    metadata:
      labels:
        app: egate-dev
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: node
        #image: vcats/egate-api:1.1.4
        image: nginx
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
          - containerPort: 80
