# apiVersion: v1
# kind: Service
# metadata:
#   name: egate-dev-service
# spec:
#   selector:
#     app: egate-dev
#   type: NodePort
#   ports:
#   - name: nginx
#     protocol: TCP
#     port: 80
#     targetPort: 80
#     nodePort: 30000