apiVersion: apps/v1
kind: Deployment
metadata:
  name: egate
  labels:
    app: egate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egate
  template:
    metadata:
      labels:
        app: egate
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: nginx
        image: vcats/egate-api:1.1.4
        env: 
          - name: MONGOURI
            value: "mongodb://admin:123asdCat@mongo-0.mongo:27017,mongo-1.mongo:27017/fintestsystem?authSource=fintestsystem&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false"
        ports:
        - containerPort: 10006
        volumeMounts:
        - name: egate-volume
          mountPath: /usr/share/egate/api
      volumes:
      - name: egate-volume
        # configMap:
        #   name: mysite-html
---
apiVersion: v1
kind: Service
metadata:
  name: egate-service
spec:
  selector:
    app: egate
  ports:
    - protocol: TCP
      port: 10006
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: egate-ingress
spec:
  entryPoints:
    
  routes:
  - kind: Rule
    match: Host(`test.e-gate.vn`) # [3]
    priority: 10                    # [4]
    services:
    - name: egate-service
      port: 10006
