apiVersion: apps/v1
kind: Deployment
metadata:
  name: egate
  labels:
    app: egate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: egate
  template:
    metadata:
      labels:
        app: egate
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: nginx
        image: vcats/egate-api:1.1.4
        env: 
          - name: MONGOURI
            value: "mongodb://admin:123asdCat@mongo-0.mongo:27017,mongo-1.mongo:27017/fintestsystem?authSource=fintestsystem&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false"
        ports:
        - containerPort: 10006
        volumeMounts:
        - name: egate-volume
          mountPath: /usr/share/egate/api
      volumes:
      - name: egate-volume
        # configMap:
        #   name: mysite-html
