apiVersion: apps/v1
kind: Deployment
metadata:
  name: egate
  labels:
    app: egate
spec:
  replicas: 5
  selector:
    matchLabels:
      app: egate
  template:
    metadata:
      labels:
        app: egate
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: api
        image: vcats/egate-api:1.2.1
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        env: 
          - name: MONGOURI
            value: "mongodb://admin:123asdCat@mongo-0.mongo:27017,mongo-1.mongo:27017/fintestsystem?authSource=fintestsystem&readPreference=primary&replicaSet=rs0"
        ports:
          - containerPort: 10006
        volumeMounts:
          - name: egate-volume
            mountPath: /usr/share/egate/api
      volumes:
      - name: egate-volume
        # configMap:
        #   name: mysite-html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: egate-admin
  labels:
    app: egate-admin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: egate-admin
  template:
    metadata:
      labels:
        app: egate-admin
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: admin
        image: vcats/egate-admin:1.1.2
        env: 
          - name: BASEAPI
            value: "https://api.e-gate.vn"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: egate-volume
          mountPath: /usr/share/egate/admin
      volumes:
        - name: egate-volume
        # configMap:
        #   name: mysite-html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: egate-socket
  labels:
    app: egate-socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egate-socket
  template:
    metadata:
      labels:
        app: egate-socket
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: socket
        image: vcats/egate-socket:1.0.1
        env: 
          - name: BASEAPI
            value: "https://socket.e-gate.vn"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: egate-volume
          mountPath: /usr/share/egate/socket
      volumes:
        - name: egate-volume
        # configMap:
        #   name: mysite-html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: egate-homepage
  labels:
    app: egate-homepage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: egate-homepage
  template:
    metadata:
      labels:
        app: egate-homepage
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: homepage
        image: vcats/egate-homepage:1.0.0
        env: 
          - name: BASEURI
            value: "https://e-gate.vn"
        ports:
        - containerPort: 15000
        volumeMounts:
        - name: egate-volume
          mountPath: /usr/share/egate/homepage
      volumes:
        - name: egate-volume
        # configMap:
        #   name: mysite-html
