apiVersion: v1
kind: Service
metadata:
  name: egate-service
spec:
  selector:
    app: egate 
  ports:
    protocol: TCP
    port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  # namespace: registry
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: test.e-gate.vn
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: egate-service
              port:
                number: 30080